security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ALTA:        ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ALTA
    
    providers:   
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            ##form_login:
            ##    provider: fos_userbundle
#                csrf_provider: form.csrf_provider
            ##    csrf_token_generator: security.csrf.token_manager
            ##    success_handler: app.handler.login_success_handler
            ##    failure_handler: app.handler.login_failure_handler
            logout:
                path:     security_logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superadmin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/update/, role: ROLE_SUPER_ADMIN }
        - { path: ^/operatorlist/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/home/, role: ROLE_USER }
        - { path: ^/private/, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }