apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: "2020-03-23T08:44:24Z"
  name: resource-limits
  namespace: sohiscert4
  resourceVersion: "626005428"
  selfLink: /api/v1/namespaces/sohiscert4/limitranges/resource-limits
  uid: 7f7e078b-6ce2-11ea-9f16-068b91999b6e
spec:
  limits:
  - max:
      cpu: "6"
      memory: 3Gi
    min:
      cpu: 5m
      memory: 80Mi
    type: Pod
  - default:
      cpu: "1"
      memory: 512Mi
    defaultRequest:
      cpu: 30m
      memory: 409Mi
    max:
      cpu: "6"
      memory: 3Gi
    min:
      cpu: 5m
      memory: 80Mi
    type: Container
  - min:
      storage: 1Gi
    type: PersistentVolumeClaim
