<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\AvesCorral;
/**
 * AvesCorralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvesCorralRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,AvesCorral::class);
    }

    public function compareEntities(AvesCorral $avesCorralxml, AvesCorral $avesCorralddbb)
    {
        $res = false;

        if ($avesCorralxml->getAvcEsp() != $avesCorralddbb->getAvcEsp()) {
            $res = true;
        }
        if ($avesCorralxml->getAvcTpn() != $avesCorralddbb->getAvcTpn()) {
            $res = true;
        }

        return $res;

    }

}
