<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\ComunicationSendRegistry;
/**
 * DocExpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunicationSendRegistryRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,ComunicationSendRegistry::class);
    }

    public function findVisitasByUserOperator($userOperator)
    {
    
            return $this->createQueryBuilder('d')
            ->select("d.visitas")
            ->andWhere('d.userOperator = :userOperator')
            ->setParameter('userOperator', $userOperator)
            ->getQuery()
            ->getResult();
         
    }


}
