<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Contact;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,Contact::class);
    }

    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param Contact $contactxml
     * @param Contact $contactddbb
     * @return bool
     */
    public function compareEntities(Contact $contactxml, Contact $contactddbb)
    {
        $res = false;

        if ($contactxml->getCnDeno() != $contactddbb->getCnDeno()) {
            $res = true;
        }
        if ($contactxml->getCnApe1() != $contactddbb->getCnApe1()) {
            $res = true;
        }
        if ($contactxml->getCnApe2() != $contactddbb->getCnApe2()) {
            $res = true;
        }
        return $res;
    }
}
