<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\CultivosRec;
/**
 * CultivosRecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultivosRecRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,CultivosRec::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param CultivosRec $cultivosrecxml
     * @param CultivosRec $cultivosrecddbb
     * @return bool
     */
    public function compareEntities(CultivosRec $cultivosrecxml, CultivosRec $cultivosrecddbb)
    {
        $res = false;

        if ($cultivosrecxml->getRuTppr() != $cultivosrecddbb->getRuTppr()) {
            $res = true;
        }
        if ($cultivosrecxml->getRuPro() != $cultivosrecddbb->getRuPro()) {
            $res = true;
        }
        if ($cultivosrecxml->getRuSitr() != $cultivosrecddbb->getRuSitr()) {
            $res = true;
        }
        if ($cultivosrecxml->getRuCul() != $cultivosrecddbb->getRuCul()) {
            $res = true;
        }
        if ($cultivosrecxml->getRuAct() != $cultivosrecddbb->getRuAct()) {
            $res = true;
        }
        if ($cultivosrecxml->getRuRc() != $cultivosrecddbb->getRuRc()) {
            $res = true;
        }

        return $res;

    }
}
