<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\CultivosRec2;
/**
 * CultivosRec2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultivosRec2Repository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,CultivosRec2::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param CultivosRec2 $cultivosrec2xml
     * @param CultivosRec2 $cultivosrec2ddbb
     * @return bool
     */
    public function compareEntities(CultivosRec2 $cultivosrec2xml, CultivosRec2 $cultivosrec2ddbb)
    {
        $res = false;

        if ($cultivosrec2xml->getRu2Sit() != $cultivosrec2ddbb->getRu2Sit()) {
            $res = true;
        }
        if ($cultivosrec2xml->getRu2Pol() != $cultivosrec2ddbb->getRu2Pol()) {
            $res = true;
        }
        if ($cultivosrec2xml->getRu2Par() != $cultivosrec2ddbb->getRu2Par()) {
            $res = true;
        }
        if ($cultivosrec2xml->getRu2Cul() != $cultivosrec2ddbb->getRu2Cul()) {
            $res = true;
        }
        if ($cultivosrec2xml->getRu2Rec() != $cultivosrec2ddbb->getRu2Rec()) {
            $res = true;
        }

        return $res;

    }

}
