<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\DocumentosFTP;
/**
 * DocExpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentFTPRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,DocumentosFTP::class);
    }

    public function findDocumentvisualizationByNbDoc($nbDoc, $op)
    {
        
        if(strpos($nbDoc,'AE')){
            
            return $this->createQueryBuilder('d')
            ->andWhere('d.nbDoc = :nbDoc1')
            ->setParameter('nbDoc1', $nbDoc)
            ->orWhere('d.nbDoc = :nbDoc2')
            ->setParameter('nbDoc2', str_replace('AE','',$nbDoc))
            ->orWhere('d.nbDoc = :nbDoc5')
            ->setParameter('nbDoc5', str_replace('/DEPARTAMENTO CERTIFICACION/1 CERTIFICADOS/3 FIRMADOS','/DEPARTAMENTO ADMINISTRACION/ARCHIVO DIGITAL',$nbDoc))
            ->getQuery()
            ->getOneOrNullResult();
        } else{
            return $this->createQueryBuilder('d')
            ->andWhere('d.nbDoc = :nbDoc3')
            ->setParameter('nbDoc3', "%" .$op . "AE%")
            ->orWhere('d.nbDoc = :nbDoc4')
            ->setParameter('nbDoc4', $nbDoc)
            ->orWhere('d.nbDoc = :nbDoc6')
            ->setParameter('nbDoc6', str_replace('/DEPARTAMENTO CERTIFICACION/1 CERTIFICADOS/3 FIRMADOS','/DEPARTAMENTO ADMINISTRACION/ARCHIVO DIGITAL',$nbDoc))
            ->getQuery()
            ->getOneOrNullResult();
            
        }  
    }


}
