<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;

use App\Entity\Especies as EntityEspecies;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Especies;
/**
 * EspeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspeciesRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,Especies::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param Especies $especiesxml
     * @param Especies $especiesddbb
     * @return bool
     */
    public function compareEntities(Especies $especiesxml, Especies $especiesddbb)
    {
        $res = false;

        if ($especiesxml->getEsDeno() != $especiesddbb->getEsDeno()) {
            $res = true;
        }

        return $res;
    }
}
