<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Ganaderias;
/**
 * GanaderiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GanaderiasRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,Ganaderias::class);
    }

    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param Ganaderias $ganaderiasxml
     * @param Ganaderias $ganaderiasddbb
     * @return bool
     */
    public function compareEntities(Ganaderias $ganaderiasxml, Ganaderias $ganaderiasddbb)
    {
        $res = false;

        if ($ganaderiasxml->getGnRc() != $ganaderiasddbb->getGnRc()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnEsp() != $ganaderiasddbb->getGnEsp()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnTpn() != $ganaderiasddbb->getGnTpn()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnPro() != $ganaderiasddbb->getGnPro()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnTpcu() != $ganaderiasddbb->getGnTpcu()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnRaza() != $ganaderiasddbb->getGnRaza()) {
            $res = true;
        }
        if ($ganaderiasxml->getGnUcap() != $ganaderiasddbb->getGnUcap()) {
            $res = true;
        }

        return $res;

    }
}
