<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\IAvesCorral;
/**
 * IAvesCorralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IAvesCorralRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,IAvesCorral::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param IAvesCorral $iavesCorralxml
     * @param IAvesCorral $iavesCorralddbb
     * @return bool
     */
    public function compareEntities(IAvesCorral $iavesCorralxml, IAvesCorral $iavesCorralddbb)
    {
        $res = false;

        if ($iavesCorralxml->getAviPrd() != $iavesCorralddbb->getAviPrd()) {
            $res = true;
        }
        if ($iavesCorralxml->getAviVar() != $iavesCorralddbb->getAviVar()) {
            $res = true;
        }
        if ($iavesCorralxml->getAviInd() != $iavesCorralddbb->getAviInd()) {
            $res = true;
        }
        if ($iavesCorralxml->getAviMar() != $iavesCorralddbb->getAviMar()) {
            $res = true;
        }

        return $res;

    }
}
