<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\ProductosPae;

/**
 * ProductosPaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosPaeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,ProductosPae::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param ProductosPae $productospaexml
     * @param ProductosPae $productospaeddbb
     * @return bool
     */
    public function compareEntities(ProductosPae $productospaexml, ProductosPae $productospaeddbb)
    {
        $res = false;

        if ($productospaexml->getPipPro() != $productospaeddbb->getPipPro()) {
            $res = true;
        }
        if ($productospaexml->getPipDsc() != $productospaeddbb->getPipDsc()) {
            $res = true;
        }
        if ($productospaexml->getPipTpp() != $productospaeddbb->getPipTpp()) {
            $res = true;
        }
        if ($productospaexml->getPipEst() != $productospaeddbb->getPipEst()) {
            $res = true;
        }

        return $res;
    }
}
