<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\ProductosIndus;
/**
 * ProductosIndusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosIndusRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,ProductosIndus::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param ProductosIndus $productosIndusxml
     * @param ProductosIndus $productosIndusddbb
     * @return bool
     */
    public function compareEntities(ProductosIndus $productosIndusxml, ProductosIndus $productosIndusddbb)
    {
        $res = false;

        if ($productosIndusxml->getPiPro() != $productosIndusddbb->getPiPro()) {
            $res = true;
        }
        if ($productosIndusxml->getPiMarca() != $productosIndusddbb->getPiMarca()) {
            $res = true;
        }
        if ($productosIndusxml->getPiDpro() != $productosIndusddbb->getPiDpro()) {
            $res = true;
        }
        if ($productosIndusxml->getPiCpro() != $productosIndusddbb->getPiCpro()) {
            $res = true;
        }

        return $res;
    }
}
