<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Productos;
/**
 * ProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,Productos::class);
    }
    
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param Productos $productosxml
     * @param Productos $productosddbb
     * @return bool
     */
    public function compareEntities(Productos $productosxml, Productos $productosddbb)
    {
        $res = false;

        if ($productosxml->getPtDeno() != $productosddbb->getPtDeno()) {
            $res = true;
        }
        if ($productosxml->getPtTc() != $productosddbb->getPtTc()) {
            $res = true;
        }
        if ($productosxml->getPtCu() != $productosddbb->getPtCu()) {
            $res = true;
        }
        if ($productosxml->getPtTi() != $productosddbb->getPtTi()) {
            $res = true;
        }

        return $res;
    }
}
