<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\ProductosG;
/**
 * ProductosGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosGRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,ProductosG::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param ProductosG $productosgxml
     * @param ProductosG $productosgddbb
     * @return bool
     */
    public function compareEntities(ProductosG $productosgxml, ProductosG $productosgddbb)
    {
        $res = false;

        if ($productosgxml->getPnDeno() != $productosgddbb->getPnDeno()) {
            $res = true;
        }

        return $res;
    }

}
