<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\NoResultException;
use App\Entity\RelationshipRegister;
/**
 * RelationshipRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipRegisterRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,RelationshipRegister::class);
    }
    /**
     * @param $reg
     * @param $sreg
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getRelationByRegSreg($reg, $sreg)
    {

        $query = $this->getEntityManager()
            ->createQuery('
				SELECT e.rlEntity,e.rlInfo FROM App\Entity\RelationshipRegister e
				WHERE e.rlReg = :reg and e.rlSreg = :sreg
				order by e.id DESC')
            ->setParameter('reg', $reg)->setParameter('sreg', $sreg);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }
}
