<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\TiposCultivos;
/**
 * TiposCultivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposCultivosRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,TiposCultivos::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param TiposCultivos $tiposcultivosxml
     * @param TiposCultivos $tiposcultivosddbb
     * @return bool
     */
    public function compareEntities(TiposCultivos $tiposcultivosxml, TiposCultivos $tiposcultivosddbb)
    {
        $res = false;

        if ($tiposcultivosxml->getTcDeno() != $tiposcultivosddbb->getTcDeno()) {
            $res = true;
        }
        if ($tiposcultivosxml->getTcRoae() != $tiposcultivosddbb->getTcRoae()) {
            $res = true;
        }

        return $res;
    }
}
