<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\TiposProducc;
/**
 * TiposProduccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposProduccRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,TiposProducc::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param TiposProducc $tiposproduccxml
     * @param TiposProducc $tiposproduccddbb
     * @return bool
     */
    public function compareEntities(TiposProducc $tiposproduccxml, TiposProducc $tiposproduccddbb)
    {
        $res = false;

        if ($tiposproduccxml->getTpnDeno() != $tiposproduccddbb->getTpnDeno()) {
            $res = true;
        }

        return $res;
    }
}
