<?php
/**
 * Copyright (c) 2016.
 * Desarrollado por Atlantic International Technology para Sohiscert
 */

namespace App\Repository;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\TiposProducto; 
/**
 * TiposProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposProductoRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
       
        parent::__construct($registry,TiposProducto::class);
    }
    /**
     * Function that compares all atributes of two instances of and Object to determine when to update the oldest one.
     *
     * @param TiposProducto $tiposproductoxml
     * @param TiposProducto $tiposproductoddbb
     * @return bool
     */
    public function compareEntities(TiposProducto $tiposproductoxml, TiposProducto $tiposproductoddbb)
    {
        $res = false;

        if ($tiposproductoxml->getTiDeno() != $tiposproductoddbb->getTiDeno()) {
            $res = true;
        }

        return $res;
    }
}
