# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    gsbase_host: sohiscert3.ddns.cyberoam.com #82.159.232.128
    gsbase_port: 8121
    gsbase_user: __*web
    gsbase_pass: S0h1scert
    gsbase_corp: shc
    gsbase_apl: gsges_shc
    gsbase_ex: shc
    gsbase_accion: consulta_xml
    gsbase_ventana: consulta-xml
    from_email: manuel.navarro@atlantic.es # Parámetro para pruebas.
    locale: es
    cartas: ['000092', '000019']
    analisis: ['000065', '000068', '000071', '000072']
    certificados: ['000000']
    compromisos: [null]
    docexptypes:
        solicitud: 'Solicitud'
        accion: 'Acción Correctiva'
        presupuesto: 'Presupuesto Aceptado'
        cuestionario: 'Cuestionario de ampliación actividad'
        programa: 'Programa de producción vegetal (PAC)'
        modificacion: 'Modificación Datos (unidad de producción, datos operador)'
        solicitudexp: 'Solicitudes Excepcionales (de semillas, manejo ganado)'
        solicutudgan: 'Solicitud de manejo de ganado'
        inclusion: 'Inclusión de productos'
        recursosrec: 'Recursos y reclamaciones'
        comunicacion: 'Comunicación incidencias ayudas agroambientales'
    plantilla_cartas: 'F155-02'
    #uploaddir: '/../../../app/logs/update/'
    path_update_logs: '%kernel.project_dir%/var/update/'
    web_root: 'https://intranet-sohiscert4.e4ff.pro-eu-west-1.openshiftapps.com/public/'
    repo_dir: '../' #'http://intranet-clientesshc.e4ff.pro-eu-west-1.openshiftapps.com'
    email_from_address: 'noreply@sohiscert.com'
    email_from_name: 'Area Privada Sohiscert'
    mail_to: 'sohiscert@sohiscert.com'
    mailer_transport: 'smtp'
    mailer_port: 587
    mailer_host: 'smtp.ionos.es'
    mailer_user: 'noreply@sohiscert.com'
    mailer_password: "Naranjo@@2020.-"
    mailer_encryption: 'tls'
    auth_mode: 'login'
    nop_conversion:
        RP: 'PAE'
        RI: 'IAE'
        RC: 'CAE'
        RG: 'GAE'
        RF: 'FAE'
        RT: 'TAE'
        RS: 'SAE'
        RN: 'NAE'
    ftp_server: 'sohiscert3.ddns.cyberoam.com'
    ftp_user_name: 'userftp1'
    ftp_user_pass: 'AtlIntTec.12'
    mailchimp_api_key: 'bccbc65594b97af78b8d502147d008b6-us19' #Elemento duplicado mailchimp.yaml
    twilio_sid: SK277c0d83b4164e6e0b86127b5518a027
    twilio_token: 9HZEOuM9aOtXTJKlZTA00NpYuJg3qRn1
    twilio_number: '(205) 809-0487'
    twilio_acconts_sid: ACc04c58a17f50ee78128156129a2ac1ee
    twilio_whatsapp_number: '+14155238886'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: true
        bind:
            $gsbase_host: '%gsbase_host%'
            $gsbase_port: '%gsbase_port%'
            $gsbase_user: '%gsbase_user'
            $gsbase_pass: '%gsbase_pass%'
            $gsbase_corp: '%gsbase_corp%'
            $gsbase_accion: '%gsbase_accion%'
            $gsbase_ventana: '%gsbase_ventana%'
            $from_email: '%from_email%'
            $locale: '%locale%'
            $cartas: '%cartas%'
            $analisis: '%analisis%'
            $certificados: '%certificados%'
            $compromisos: '%compromisos%'
            $docexptypes: '%docexptypes%'
            $plantilla_cartas: '%plantilla_cartas%'
            $path_update_logs: '%path_update_logs%'
            $web_root: '%web_root%'
            $repo_dir: '%repo_dir%'
            $email_from_address: '%email_from_address%'
            $email_from_name: '%email_from_name%'
            $mail_to: '%mail_to%'
            $mailer_transport: '%mailer_transport%'
            $mailer_port: '%mailer_port%'
            $mailer_host: '%mailer_host%'
            $mailer_user: '%mailer_user%'
            $mailer_password: '%mailer_password%'
            $mailer_encryption: '%mailer_encryption%'
            $auth_mode: '%auth_mode%'
            $nop_conversion: '%nop_conversion%'
            $ftp_server: '%ftp_server%'
            $ftp_user_name: '%ftp_user_name%'
            $ftp_user_pass: '%ftp_user_pass%'
            $mailchimp_api_key: '%mailchimp_api_key%'
            $twilio_sid: '%twilio_sid'
            $twilio_token: '%twilio_token'
            $twilio_number: '%twilio_number'
            $twilio_acconts_sid: '%twilio_acconts_sid'
            $twilio_whatsapp_number: '%twilio_whatsapp_number'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Mailchimp,Twilio,Esendex,Mailer,GsBase,Command,Ftp,Tools,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    gsbase:
        class: App\GsBase\GsBase
        arguments: ["%gsbase_host%","%gsbase_port%","%gsbase_user%","%gsbase_pass%","%gsbase_corp%","%gsbase_apl%","%gsbase_ex%","%gsbase_accion%","%gsbase_ventana%"]
        tags: [name: 'gsbase']

    toolsupdate:
        class: App\Tools\ToolsUpdate
        arguments: ["@service_container",'@doctrine.orm.entity_manager','@jms_serializer']
        tags: [name: 'toolsupdate']
    
    gsbasexml:
        class: App\GsBase\GsBaseXml
        arguments: ["@service_container"]
        tags: [name: 'gsbasexml']

    app.mailer.service:
        class: App\Mailer\Mailer
        arguments: ["@mailer", "@twig",'%email_from_address%','%email_from_name%','%mail_to%']
        tags: ['app.mailer.service']
#===================================================================================================    

    App\Command\EmailUpdateDocFactuCommand:
        tags: { name: 'console.command', command: 'email:emaildocfactu:send'}
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

    App\Command\EmailUpdateDocConcluCommand:
        tags: { name: 'console.command', command: 'email:emaildoccon:send'}
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

    App\Command\EmailUpdateDocCommand:
        tags: { name: 'console.command', command: 'email:emaildoc:send'}
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

    App\Command\EmaildocanaSendCommand:
        tags: { name: 'console.command', command: "email:emaildocana:send" }
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

    App\Command\EmaildoccarSendCommand:
        tags: { name: 'console.command', command: "email:emaildoccar:send" }
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

    App\Command\EmailUpdateDocCertiCommand:
        tags: { name: 'console.command', command: "email:emaildoccerti:send" }
        arguments: ['%path_update_logs%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%','@mailer','@doctrine.orm.entity_manager']

#=======================================================================================================================

    App\Command\GsBaseConnectCommand:
        tags:
            - { name: 'console.command', command: 'gsbase:connect'}
        arguments: ['%path_update_logs%', '@gsbase']

    App\Command\UpdateRegisterCommand:
        tags: { name: 'console.command', command: 'gsbase:update:registro'}
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml']

    App\Command\UpdateProductosPaeCommand:
        tags: { name: 'console.command', command: "gsbase:update:productospae" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']   

    App\Command\UpdateProductosIndusCommand:
        tags: { name: 'console.command', command: "gsbase:update:productosindus" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateProductosCommand:
        tags: { name: 'console.command', command: "gsbase:update:productos" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateOperatorEntityCommand:
        tags: { name: 'console.command', command: "gsbase:update:operatorentity" }
        arguments: ['%path_update_logs%','@doctrine.orm.entity_manager']

    App\Command\UpdateOperatorCommand:
        tags: { name: 'console.command', command: "gsbase:update:operator" }
        arguments: ['%path_update_logs%','@gsbase', '@gsbasexml','@jms_serializer','@doctrine.orm.entity_manager']

    App\Command\UpdateIndustriasCommand:
        tags: { name: 'console.command', command: "gsbase:update:industrias" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateGanaderiasCommand:
        tags: { name: 'console.command', command: "gsbase:update:ganaderias" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateDateDocumentsOperatorsClientCommand:
        tags: { name: 'console.command', command: "gsbase:update:datedocuments" }       
    
    App\Command\UpdateCultivosRecCommand:
        tags: { name: 'console.command', command: "gsbase:update:cultivosrec" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']         

    App\Command\UpdateCultivosRecBisCommand:
        tags: { name: 'console.command', command: "gsbase:update:cultivosrecbis" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateCultivosRec2Command:
        tags: { name: 'console.command', command: "gsbase:update:cultivosrec2" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateContactCommand:
        tags: { name: 'console.command', command: "gsbase:update:contact" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateClientCommand:
        tags: { name: 'console.command', command: "gsbase:update:client" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateBasicInfoCommand:
        tags: { name: 'console.command', command: "gsbase:update:basicinfo" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\UpdateAvesCorralCommand:
        tags: { name: 'console.command', command: "gsbase:update:avescorral" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

    App\Command\RemoveOperatorCommand:
        tags: { name: 'console.command', command: "gsbase:remove:operator" }
        arguments: ['%path_update_logs%','@gsbase', '@gsbasexml','@jms_serializer','@doctrine.orm.entity_manager']


#=======================================================================================================================

    App\Command\IniUserOperatorsCommand:
        tags: { name: 'console.command', command: "app:ini:batch:useroperators" }
        arguments: ['%path_update_logs%','@doctrine.orm.entity_manager']
        
    App\Command\IniContactCommand:
        tags: { name: 'console.command', command: "app:ini:batch:clientscontact" }
        arguments: ['%path_update_logs%','@gsbase', '@gsbasexml','@jms_serializer','@doctrine.orm.entity_manager']

    App\Command\IniClientOperatorsCommand:
        tags: { name: 'console.command', command: "app:ini:batch:clientuseroperators" }
        arguments: ['%path_update_logs%','@toolsupdate','@gsbase', '@gsbasexml','@doctrine.orm.entity_manager']

#===================================================================================================
    
    app.ftp.service:
        class: App\Ftp\Ftp
        arguments: [ '%nop_conversion%','%ftp_server%','%ftp_user_name%', '%ftp_user_pass%' ]

    App\Entity\AccessLog:
        class: App\Entity\AccessLog

    LoginAuthenticator:
        class:  App\Security\LoginAuthenticator
        arguments: [ '@doctrine.orm.entity_manager',"@router"] 

#===================================================================================================

    App\Repository\OperatorRepository:
        tags: ['doctrine.repository_service']
    App\Repository\OpNopTransformRepository:
        tags: ['doctrine.repository_service']
    App\Repository\UserOperatorRepository:
        tags: ['doctrine.repository_service']
    App\Repository\UpdateLogRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ProductosRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ProductosGRepository:
        tags: ['doctrine.repository_service']
    App\Repository\IndustriasRepository:
        tags: ['doctrine.repository_service']
    App\Repository\RelationshipRegisterRepository:
        tags: ['doctrine.repository_service']
    App\Repository\UserRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ClientRepository:
        tags: ['doctrine.repository_service']
    App\Repository\TiposCultivosRepository:
        tags: ['doctrine.repository_service']
    App\Repository\TiposProductoRepository:
        tags: ['doctrine.repository_service']
    App\Repository\CultivosRecRepository:
        tags: ['doctrine.repository_service']
    App\Repository\CultivosRec2Repository:
        tags: ['doctrine.repository_service']    
    App\Repository\CultivosRepository:
        tags: ['doctrine.repository_service']
    App\Repository\EspeciesRepository:
        tags: ['doctrine.repository_service']
    App\Repository\TiposProduccRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ActividadesIRepository:
        tags: ['doctrine.repository_service']
    App\Repository\RegisterRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ProductosPaeRepository:
        tags: ['doctrine.repository_service']
    App\Repository\GanaderiasRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ContactRepository:
        tags: ['doctrine.repository_service']
    App\Repository\DocumentFTPRepository:
        tags: ['doctrine.repository_service']
    App\Repository\ComunicationSendRegistryRepository:
        tags: ['doctrine.repository_service']    


#======================================================================
   
    App\Mailchimp\Provider\MailchimpDynamicProvider:
        arguments: [App\Repository\UserOperatorRepository,"@service_container"] 

    welp_mailchimp.provider.factory:
        class: App\Mailchimp\Provider\MailchimpDynamicProvider
    doctrine.list.provider:
        class: App\Mailchimp\Provider\DoctrineListProvider
        public: true
        arguments: ['@doctrine.orm.entity_manager','App\Entity\UserOperator','@welp_mailchimp.provider.factory']
        
    App\Mailchimp\Provider\DoctrineListProvider: '@doctrine.list.provider'

    twilio.client:
       class: Twilio\Rest\Client
       arguments: ['%twilio_sid%', '%twilio_token%','@doctrine']
  
   # Add an alias for the twilio.client service
    Twilio\Rest\Client: '@twilio.client'

    App\Twilio\TwilioController:
        class: App\Twilio\TwilioController
        arguments: [ '@doctrine.orm.entity_manager']

   ## App\SmsUp\SmsUpController: '@smsup.smsupapi.sender'
